package com.woniu.mapper;

import com.woniu.entity.Beinmortgage;
import com.woniu.entity.BeinmortgageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BeinmortgageMapper {

	void deleteByRoomid(Integer roomid);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table beinmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	long countByExample(BeinmortgageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table beinmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int deleteByExample(BeinmortgageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table beinmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int deleteByPrimaryKey(Integer bmid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table beinmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int insert(Beinmortgage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table beinmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int insertSelective(Beinmortgage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table beinmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	List<Beinmortgage> selectByExample(BeinmortgageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table beinmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	Beinmortgage selectByPrimaryKey(Integer bmid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table beinmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Beinmortgage record, @Param("example") BeinmortgageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table beinmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByExample(@Param("record") Beinmortgage record, @Param("example") BeinmortgageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table beinmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByPrimaryKeySelective(Beinmortgage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table beinmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByPrimaryKey(Beinmortgage record);
}