package com.woniu.mapper;

import com.woniu.entity.Client;
import com.woniu.entity.ClientExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface ClientMapper {
	
	@Select("select * from client where clientid = #{clientid}")
	Client findById(Integer clientid);
	
	Client findByNameAndIdcard(Client client);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	long countByExample(ClientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int deleteByExample(ClientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int deleteByPrimaryKey(Integer clientid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int insert(Client record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int insertSelective(Client record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	List<Client> selectByExample(ClientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	Client selectByPrimaryKey(Integer clientid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Client record, @Param("example") ClientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByExample(@Param("record") Client record, @Param("example") ClientExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByPrimaryKeySelective(Client record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table client
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByPrimaryKey(Client record);
}