package com.woniu.mapper;

import com.woniu.entity.Closeregistration;
import com.woniu.entity.CloseregistrationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CloseregistrationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table closeregistration
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	long countByExample(CloseregistrationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table closeregistration
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int deleteByExample(CloseregistrationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table closeregistration
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table closeregistration
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int insert(Closeregistration record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table closeregistration
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int insertSelective(Closeregistration record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table closeregistration
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	List<Closeregistration> selectByExample(CloseregistrationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table closeregistration
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	Closeregistration selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table closeregistration
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Closeregistration record,
			@Param("example") CloseregistrationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table closeregistration
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByExample(@Param("record") Closeregistration record, @Param("example") CloseregistrationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table closeregistration
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByPrimaryKeySelective(Closeregistration record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table closeregistration
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByPrimaryKey(Closeregistration record);
}