package com.woniu.mapper;

import com.woniu.entity.Existmortgage;
import com.woniu.entity.ExistmortgageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExistmortgageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table existmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	long countByExample(ExistmortgageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table existmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int deleteByExample(ExistmortgageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table existmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int deleteByPrimaryKey(Integer emid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table existmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int insert(Existmortgage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table existmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int insertSelective(Existmortgage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table existmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	List<Existmortgage> selectByExample(ExistmortgageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table existmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	Existmortgage selectByPrimaryKey(Integer emid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table existmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Existmortgage record, @Param("example") ExistmortgageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table existmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByExample(@Param("record") Existmortgage record, @Param("example") ExistmortgageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table existmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByPrimaryKeySelective(Existmortgage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table existmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByPrimaryKey(Existmortgage record);
}