package com.woniu.mapper;

import com.woniu.entity.Gainingmethod;
import com.woniu.entity.GainingmethodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GainingmethodMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gainingmethod
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	long countByExample(GainingmethodExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gainingmethod
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int deleteByExample(GainingmethodExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gainingmethod
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int deleteByPrimaryKey(Integer gid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gainingmethod
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int insert(Gainingmethod record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gainingmethod
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int insertSelective(Gainingmethod record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gainingmethod
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	List<Gainingmethod> selectByExample(GainingmethodExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gainingmethod
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	Gainingmethod selectByPrimaryKey(Integer gid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gainingmethod
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Gainingmethod record, @Param("example") GainingmethodExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gainingmethod
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByExample(@Param("record") Gainingmethod record, @Param("example") GainingmethodExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gainingmethod
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByPrimaryKeySelective(Gainingmethod record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table gainingmethod
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByPrimaryKey(Gainingmethod record);
}