package com.woniu.mapper;

import com.woniu.entity.Otherregistration;
import com.woniu.entity.OtherregistrationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OtherregistrationMapper {

	void deleteByRoomid(Integer roomid);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table otherregistration
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	long countByExample(OtherregistrationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table otherregistration
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int deleteByExample(OtherregistrationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table otherregistration
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table otherregistration
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int insert(Otherregistration record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table otherregistration
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int insertSelective(Otherregistration record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table otherregistration
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	List<Otherregistration> selectByExample(OtherregistrationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table otherregistration
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	Otherregistration selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table otherregistration
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Otherregistration record,
			@Param("example") OtherregistrationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table otherregistration
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByExample(@Param("record") Otherregistration record, @Param("example") OtherregistrationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table otherregistration
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByPrimaryKeySelective(Otherregistration record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table otherregistration
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	int updateByPrimaryKey(Otherregistration record);
}