package com.woniu.mapper;

import com.woniu.entity.Publicbuildings;
import com.woniu.entity.PublicbuildingsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PublicbuildingsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publicbuildings
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    long countByExample(PublicbuildingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publicbuildings
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    int deleteByExample(PublicbuildingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publicbuildings
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    int deleteByPrimaryKey(Integer pbid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publicbuildings
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    int insert(Publicbuildings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publicbuildings
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    int insertSelective(Publicbuildings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publicbuildings
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    List<Publicbuildings> selectByExample(PublicbuildingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publicbuildings
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    Publicbuildings selectByPrimaryKey(Integer pbid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publicbuildings
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") Publicbuildings record, @Param("example") PublicbuildingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publicbuildings
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    int updateByExample(@Param("record") Publicbuildings record, @Param("example") PublicbuildingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publicbuildings
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    int updateByPrimaryKeySelective(Publicbuildings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publicbuildings
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    int updateByPrimaryKey(Publicbuildings record);
}