package com.woniu.mapper;

import com.woniu.entity.Registertemporary;
import com.woniu.entity.RegistertemporaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegistertemporaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registertemporary
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    long countByExample(RegistertemporaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registertemporary
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    int deleteByExample(RegistertemporaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registertemporary
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    int deleteByPrimaryKey(Integer rtid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registertemporary
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    int insert(Registertemporary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registertemporary
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    int insertSelective(Registertemporary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registertemporary
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    List<Registertemporary> selectByExample(RegistertemporaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registertemporary
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    Registertemporary selectByPrimaryKey(Integer rtid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registertemporary
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") Registertemporary record, @Param("example") RegistertemporaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registertemporary
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    int updateByExample(@Param("record") Registertemporary record, @Param("example") RegistertemporaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registertemporary
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    int updateByPrimaryKeySelective(Registertemporary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registertemporary
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    int updateByPrimaryKey(Registertemporary record);
}