package com.woniu.mapper;

import com.woniu.entity.Roomtype;
import com.woniu.entity.RoomtypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoomtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    long countByExample(RoomtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    int deleteByExample(RoomtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    int deleteByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    int insert(Roomtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    int insertSelective(Roomtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    List<Roomtype> selectByExample(RoomtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    Roomtype selectByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") Roomtype record, @Param("example") RoomtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    int updateByExample(@Param("record") Roomtype record, @Param("example") RoomtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    int updateByPrimaryKeySelective(Roomtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtype
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    int updateByPrimaryKey(Roomtype record);
}