package com.woniu.mapper;

import com.woniu.entity.Servicesharetemporary;
import com.woniu.entity.ServicesharetemporaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServicesharetemporaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicesharetemporary
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    long countByExample(ServicesharetemporaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicesharetemporary
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    int deleteByExample(ServicesharetemporaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicesharetemporary
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    int deleteByPrimaryKey(Integer shareid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicesharetemporary
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    int insert(Servicesharetemporary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicesharetemporary
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    int insertSelective(Servicesharetemporary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicesharetemporary
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    List<Servicesharetemporary> selectByExample(ServicesharetemporaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicesharetemporary
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    Servicesharetemporary selectByPrimaryKey(Integer shareid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicesharetemporary
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") Servicesharetemporary record, @Param("example") ServicesharetemporaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicesharetemporary
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    int updateByExample(@Param("record") Servicesharetemporary record, @Param("example") ServicesharetemporaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicesharetemporary
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    int updateByPrimaryKeySelective(Servicesharetemporary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servicesharetemporary
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    int updateByPrimaryKey(Servicesharetemporary record);
}