package com.woniu.entity;

public class Buildingstructure {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buildingstructure.bsid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer bsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buildingstructure.bsname
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private String bsname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buildingstructure.bsid
	 * @return  the value of buildingstructure.bsid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getBsid() {
		return bsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buildingstructure.bsid
	 * @param bsid  the value for buildingstructure.bsid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setBsid(Integer bsid) {
		this.bsid = bsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buildingstructure.bsname
	 * @return  the value of buildingstructure.bsname
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public String getBsname() {
		return bsname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buildingstructure.bsname
	 * @param bsname  the value for buildingstructure.bsname
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setBsname(String bsname) {
		this.bsname = bsname;
	}
}