package com.woniu.entity;

import java.util.ArrayList;
import java.util.List;

public class BuildingstructureExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table buildingstructure
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table buildingstructure
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table buildingstructure
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buildingstructure
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public BuildingstructureExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buildingstructure
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buildingstructure
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buildingstructure
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buildingstructure
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buildingstructure
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buildingstructure
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buildingstructure
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buildingstructure
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buildingstructure
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table buildingstructure
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table buildingstructure
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andBsidIsNull() {
			addCriterion("bsid is null");
			return (Criteria) this;
		}

		public Criteria andBsidIsNotNull() {
			addCriterion("bsid is not null");
			return (Criteria) this;
		}

		public Criteria andBsidEqualTo(Integer value) {
			addCriterion("bsid =", value, "bsid");
			return (Criteria) this;
		}

		public Criteria andBsidNotEqualTo(Integer value) {
			addCriterion("bsid <>", value, "bsid");
			return (Criteria) this;
		}

		public Criteria andBsidGreaterThan(Integer value) {
			addCriterion("bsid >", value, "bsid");
			return (Criteria) this;
		}

		public Criteria andBsidGreaterThanOrEqualTo(Integer value) {
			addCriterion("bsid >=", value, "bsid");
			return (Criteria) this;
		}

		public Criteria andBsidLessThan(Integer value) {
			addCriterion("bsid <", value, "bsid");
			return (Criteria) this;
		}

		public Criteria andBsidLessThanOrEqualTo(Integer value) {
			addCriterion("bsid <=", value, "bsid");
			return (Criteria) this;
		}

		public Criteria andBsidIn(List<Integer> values) {
			addCriterion("bsid in", values, "bsid");
			return (Criteria) this;
		}

		public Criteria andBsidNotIn(List<Integer> values) {
			addCriterion("bsid not in", values, "bsid");
			return (Criteria) this;
		}

		public Criteria andBsidBetween(Integer value1, Integer value2) {
			addCriterion("bsid between", value1, value2, "bsid");
			return (Criteria) this;
		}

		public Criteria andBsidNotBetween(Integer value1, Integer value2) {
			addCriterion("bsid not between", value1, value2, "bsid");
			return (Criteria) this;
		}

		public Criteria andBsnameIsNull() {
			addCriterion("bsname is null");
			return (Criteria) this;
		}

		public Criteria andBsnameIsNotNull() {
			addCriterion("bsname is not null");
			return (Criteria) this;
		}

		public Criteria andBsnameEqualTo(String value) {
			addCriterion("bsname =", value, "bsname");
			return (Criteria) this;
		}

		public Criteria andBsnameNotEqualTo(String value) {
			addCriterion("bsname <>", value, "bsname");
			return (Criteria) this;
		}

		public Criteria andBsnameGreaterThan(String value) {
			addCriterion("bsname >", value, "bsname");
			return (Criteria) this;
		}

		public Criteria andBsnameGreaterThanOrEqualTo(String value) {
			addCriterion("bsname >=", value, "bsname");
			return (Criteria) this;
		}

		public Criteria andBsnameLessThan(String value) {
			addCriterion("bsname <", value, "bsname");
			return (Criteria) this;
		}

		public Criteria andBsnameLessThanOrEqualTo(String value) {
			addCriterion("bsname <=", value, "bsname");
			return (Criteria) this;
		}

		public Criteria andBsnameLike(String value) {
			addCriterion("bsname like", value, "bsname");
			return (Criteria) this;
		}

		public Criteria andBsnameNotLike(String value) {
			addCriterion("bsname not like", value, "bsname");
			return (Criteria) this;
		}

		public Criteria andBsnameIn(List<String> values) {
			addCriterion("bsname in", values, "bsname");
			return (Criteria) this;
		}

		public Criteria andBsnameNotIn(List<String> values) {
			addCriterion("bsname not in", values, "bsname");
			return (Criteria) this;
		}

		public Criteria andBsnameBetween(String value1, String value2) {
			addCriterion("bsname between", value1, value2, "bsname");
			return (Criteria) this;
		}

		public Criteria andBsnameNotBetween(String value1, String value2) {
			addCriterion("bsname not between", value1, value2, "bsname");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table buildingstructure
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table buildingstructure
     *
     * @mbg.generated do_not_delete_during_merge Mon Aug 19 15:45:31 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}