package com.woniu.entity;

public class Buildingarea {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buildingarea.bid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer bid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buildingarea.bname
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private String bname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column buildingarea.zid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer zid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buildingarea.bid
	 * @return  the value of buildingarea.bid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getBid() {
		return bid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buildingarea.bid
	 * @param bid  the value for buildingarea.bid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setBid(Integer bid) {
		this.bid = bid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buildingarea.bname
	 * @return  the value of buildingarea.bname
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public String getBname() {
		return bname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buildingarea.bname
	 * @param bname  the value for buildingarea.bname
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setBname(String bname) {
		this.bname = bname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column buildingarea.zid
	 * @return  the value of buildingarea.zid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getZid() {
		return zid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column buildingarea.zid
	 * @param zid  the value for buildingarea.zid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setZid(Integer zid) {
		this.zid = zid;
	}
}