package com.woniu.entity;

import java.util.ArrayList;
import java.util.List;

public class Client {
	
	
	private Serviceshare serviceshares;
	
	

	

	public Serviceshare getServiceshares() {
		return serviceshares;
	}

	public void setServiceshares(Serviceshare serviceshares) {
		this.serviceshares = serviceshares;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client.clientid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer clientid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client.clientname
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private String clientname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client.address
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client.idcard
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private String idcard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client.phone
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column client.zid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer zid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client.clientid
	 * @return  the value of client.clientid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getClientid() {
		return clientid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client.clientid
	 * @param clientid  the value for client.clientid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setClientid(Integer clientid) {
		this.clientid = clientid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client.clientname
	 * @return  the value of client.clientname
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public String getClientname() {
		return clientname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client.clientname
	 * @param clientname  the value for client.clientname
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setClientname(String clientname) {
		this.clientname = clientname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client.address
	 * @return  the value of client.address
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client.address
	 * @param address  the value for client.address
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client.idcard
	 * @return  the value of client.idcard
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public String getIdcard() {
		return idcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client.idcard
	 * @param idcard  the value for client.idcard
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client.phone
	 * @return  the value of client.phone
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client.phone
	 * @param phone  the value for client.phone
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column client.zid
	 * @return  the value of client.zid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getZid() {
		return zid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column client.zid
	 * @param zid  the value for client.zid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setZid(Integer zid) {
		this.zid = zid;
	}
	
	@Override
	public String toString() {
		return clientname;
	}
	
}