package com.woniu.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CloseregistrationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table closeregistration
     *
     * @mbggenerated Thu Aug 22 18:58:51 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table closeregistration
     *
     * @mbggenerated Thu Aug 22 18:58:51 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table closeregistration
     *
     * @mbggenerated Thu Aug 22 18:58:51 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table closeregistration
     *
     * @mbggenerated Thu Aug 22 18:58:51 CST 2019
     */
    public CloseregistrationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table closeregistration
     *
     * @mbggenerated Thu Aug 22 18:58:51 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table closeregistration
     *
     * @mbggenerated Thu Aug 22 18:58:51 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table closeregistration
     *
     * @mbggenerated Thu Aug 22 18:58:51 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table closeregistration
     *
     * @mbggenerated Thu Aug 22 18:58:51 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table closeregistration
     *
     * @mbggenerated Thu Aug 22 18:58:51 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table closeregistration
     *
     * @mbggenerated Thu Aug 22 18:58:51 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table closeregistration
     *
     * @mbggenerated Thu Aug 22 18:58:51 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table closeregistration
     *
     * @mbggenerated Thu Aug 22 18:58:51 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table closeregistration
     *
     * @mbggenerated Thu Aug 22 18:58:51 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table closeregistration
     *
     * @mbggenerated Thu Aug 22 18:58:51 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table closeregistration
     *
     * @mbggenerated Thu Aug 22 18:58:51 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andServiceidIsNull() {
            addCriterion("serviceid is null");
            return (Criteria) this;
        }

        public Criteria andServiceidIsNotNull() {
            addCriterion("serviceid is not null");
            return (Criteria) this;
        }

        public Criteria andServiceidEqualTo(Integer value) {
            addCriterion("serviceid =", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidNotEqualTo(Integer value) {
            addCriterion("serviceid <>", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidGreaterThan(Integer value) {
            addCriterion("serviceid >", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidGreaterThanOrEqualTo(Integer value) {
            addCriterion("serviceid >=", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidLessThan(Integer value) {
            addCriterion("serviceid <", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidLessThanOrEqualTo(Integer value) {
            addCriterion("serviceid <=", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidIn(List<Integer> values) {
            addCriterion("serviceid in", values, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidNotIn(List<Integer> values) {
            addCriterion("serviceid not in", values, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidBetween(Integer value1, Integer value2) {
            addCriterion("serviceid between", value1, value2, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidNotBetween(Integer value1, Integer value2) {
            addCriterion("serviceid not between", value1, value2, "serviceid");
            return (Criteria) this;
        }

        public Criteria andCloseofficeidIsNull() {
            addCriterion("closeofficeid is null");
            return (Criteria) this;
        }

        public Criteria andCloseofficeidIsNotNull() {
            addCriterion("closeofficeid is not null");
            return (Criteria) this;
        }

        public Criteria andCloseofficeidEqualTo(Integer value) {
            addCriterion("closeofficeid =", value, "closeofficeid");
            return (Criteria) this;
        }

        public Criteria andCloseofficeidNotEqualTo(Integer value) {
            addCriterion("closeofficeid <>", value, "closeofficeid");
            return (Criteria) this;
        }

        public Criteria andCloseofficeidGreaterThan(Integer value) {
            addCriterion("closeofficeid >", value, "closeofficeid");
            return (Criteria) this;
        }

        public Criteria andCloseofficeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("closeofficeid >=", value, "closeofficeid");
            return (Criteria) this;
        }

        public Criteria andCloseofficeidLessThan(Integer value) {
            addCriterion("closeofficeid <", value, "closeofficeid");
            return (Criteria) this;
        }

        public Criteria andCloseofficeidLessThanOrEqualTo(Integer value) {
            addCriterion("closeofficeid <=", value, "closeofficeid");
            return (Criteria) this;
        }

        public Criteria andCloseofficeidIn(List<Integer> values) {
            addCriterion("closeofficeid in", values, "closeofficeid");
            return (Criteria) this;
        }

        public Criteria andCloseofficeidNotIn(List<Integer> values) {
            addCriterion("closeofficeid not in", values, "closeofficeid");
            return (Criteria) this;
        }

        public Criteria andCloseofficeidBetween(Integer value1, Integer value2) {
            addCriterion("closeofficeid between", value1, value2, "closeofficeid");
            return (Criteria) this;
        }

        public Criteria andCloseofficeidNotBetween(Integer value1, Integer value2) {
            addCriterion("closeofficeid not between", value1, value2, "closeofficeid");
            return (Criteria) this;
        }

        public Criteria andClosefileIsNull() {
            addCriterion("closefile is null");
            return (Criteria) this;
        }

        public Criteria andClosefileIsNotNull() {
            addCriterion("closefile is not null");
            return (Criteria) this;
        }

        public Criteria andClosefileEqualTo(String value) {
            addCriterion("closefile =", value, "closefile");
            return (Criteria) this;
        }

        public Criteria andClosefileNotEqualTo(String value) {
            addCriterion("closefile <>", value, "closefile");
            return (Criteria) this;
        }

        public Criteria andClosefileGreaterThan(String value) {
            addCriterion("closefile >", value, "closefile");
            return (Criteria) this;
        }

        public Criteria andClosefileGreaterThanOrEqualTo(String value) {
            addCriterion("closefile >=", value, "closefile");
            return (Criteria) this;
        }

        public Criteria andClosefileLessThan(String value) {
            addCriterion("closefile <", value, "closefile");
            return (Criteria) this;
        }

        public Criteria andClosefileLessThanOrEqualTo(String value) {
            addCriterion("closefile <=", value, "closefile");
            return (Criteria) this;
        }

        public Criteria andClosefileLike(String value) {
            addCriterion("closefile like", value, "closefile");
            return (Criteria) this;
        }

        public Criteria andClosefileNotLike(String value) {
            addCriterion("closefile not like", value, "closefile");
            return (Criteria) this;
        }

        public Criteria andClosefileIn(List<String> values) {
            addCriterion("closefile in", values, "closefile");
            return (Criteria) this;
        }

        public Criteria andClosefileNotIn(List<String> values) {
            addCriterion("closefile not in", values, "closefile");
            return (Criteria) this;
        }

        public Criteria andClosefileBetween(String value1, String value2) {
            addCriterion("closefile between", value1, value2, "closefile");
            return (Criteria) this;
        }

        public Criteria andClosefileNotBetween(String value1, String value2) {
            addCriterion("closefile not between", value1, value2, "closefile");
            return (Criteria) this;
        }

        public Criteria andClosefilenumberIsNull() {
            addCriterion("closefilenumber is null");
            return (Criteria) this;
        }

        public Criteria andClosefilenumberIsNotNull() {
            addCriterion("closefilenumber is not null");
            return (Criteria) this;
        }

        public Criteria andClosefilenumberEqualTo(String value) {
            addCriterion("closefilenumber =", value, "closefilenumber");
            return (Criteria) this;
        }

        public Criteria andClosefilenumberNotEqualTo(String value) {
            addCriterion("closefilenumber <>", value, "closefilenumber");
            return (Criteria) this;
        }

        public Criteria andClosefilenumberGreaterThan(String value) {
            addCriterion("closefilenumber >", value, "closefilenumber");
            return (Criteria) this;
        }

        public Criteria andClosefilenumberGreaterThanOrEqualTo(String value) {
            addCriterion("closefilenumber >=", value, "closefilenumber");
            return (Criteria) this;
        }

        public Criteria andClosefilenumberLessThan(String value) {
            addCriterion("closefilenumber <", value, "closefilenumber");
            return (Criteria) this;
        }

        public Criteria andClosefilenumberLessThanOrEqualTo(String value) {
            addCriterion("closefilenumber <=", value, "closefilenumber");
            return (Criteria) this;
        }

        public Criteria andClosefilenumberLike(String value) {
            addCriterion("closefilenumber like", value, "closefilenumber");
            return (Criteria) this;
        }

        public Criteria andClosefilenumberNotLike(String value) {
            addCriterion("closefilenumber not like", value, "closefilenumber");
            return (Criteria) this;
        }

        public Criteria andClosefilenumberIn(List<String> values) {
            addCriterion("closefilenumber in", values, "closefilenumber");
            return (Criteria) this;
        }

        public Criteria andClosefilenumberNotIn(List<String> values) {
            addCriterion("closefilenumber not in", values, "closefilenumber");
            return (Criteria) this;
        }

        public Criteria andClosefilenumberBetween(String value1, String value2) {
            addCriterion("closefilenumber between", value1, value2, "closefilenumber");
            return (Criteria) this;
        }

        public Criteria andClosefilenumberNotBetween(String value1, String value2) {
            addCriterion("closefilenumber not between", value1, value2, "closefilenumber");
            return (Criteria) this;
        }

        public Criteria andClosetimeIsNull() {
            addCriterion("closetime is null");
            return (Criteria) this;
        }

        public Criteria andClosetimeIsNotNull() {
            addCriterion("closetime is not null");
            return (Criteria) this;
        }

        public Criteria andClosetimeEqualTo(Date value) {
            addCriterion("closetime =", value, "closetime");
            return (Criteria) this;
        }

        public Criteria andClosetimeNotEqualTo(Date value) {
            addCriterion("closetime <>", value, "closetime");
            return (Criteria) this;
        }

        public Criteria andClosetimeGreaterThan(Date value) {
            addCriterion("closetime >", value, "closetime");
            return (Criteria) this;
        }

        public Criteria andClosetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("closetime >=", value, "closetime");
            return (Criteria) this;
        }

        public Criteria andClosetimeLessThan(Date value) {
            addCriterion("closetime <", value, "closetime");
            return (Criteria) this;
        }

        public Criteria andClosetimeLessThanOrEqualTo(Date value) {
            addCriterion("closetime <=", value, "closetime");
            return (Criteria) this;
        }

        public Criteria andClosetimeIn(List<Date> values) {
            addCriterion("closetime in", values, "closetime");
            return (Criteria) this;
        }

        public Criteria andClosetimeNotIn(List<Date> values) {
            addCriterion("closetime not in", values, "closetime");
            return (Criteria) this;
        }

        public Criteria andClosetimeBetween(Date value1, Date value2) {
            addCriterion("closetime between", value1, value2, "closetime");
            return (Criteria) this;
        }

        public Criteria andClosetimeNotBetween(Date value1, Date value2) {
            addCriterion("closetime not between", value1, value2, "closetime");
            return (Criteria) this;
        }

        public Criteria andClosedateIsNull() {
            addCriterion("closedate is null");
            return (Criteria) this;
        }

        public Criteria andClosedateIsNotNull() {
            addCriterion("closedate is not null");
            return (Criteria) this;
        }

        public Criteria andClosedateEqualTo(Date value) {
            addCriterion("closedate =", value, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateNotEqualTo(Date value) {
            addCriterion("closedate <>", value, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateGreaterThan(Date value) {
            addCriterion("closedate >", value, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateGreaterThanOrEqualTo(Date value) {
            addCriterion("closedate >=", value, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateLessThan(Date value) {
            addCriterion("closedate <", value, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateLessThanOrEqualTo(Date value) {
            addCriterion("closedate <=", value, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateIn(List<Date> values) {
            addCriterion("closedate in", values, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateNotIn(List<Date> values) {
            addCriterion("closedate not in", values, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateBetween(Date value1, Date value2) {
            addCriterion("closedate between", value1, value2, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateNotBetween(Date value1, Date value2) {
            addCriterion("closedate not between", value1, value2, "closedate");
            return (Criteria) this;
        }

        public Criteria andRegistertimeIsNull() {
            addCriterion("registertime is null");
            return (Criteria) this;
        }

        public Criteria andRegistertimeIsNotNull() {
            addCriterion("registertime is not null");
            return (Criteria) this;
        }

        public Criteria andRegistertimeEqualTo(Date value) {
            addCriterion("registertime =", value, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeNotEqualTo(Date value) {
            addCriterion("registertime <>", value, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeGreaterThan(Date value) {
            addCriterion("registertime >", value, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeGreaterThanOrEqualTo(Date value) {
            addCriterion("registertime >=", value, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeLessThan(Date value) {
            addCriterion("registertime <", value, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeLessThanOrEqualTo(Date value) {
            addCriterion("registertime <=", value, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeIn(List<Date> values) {
            addCriterion("registertime in", values, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeNotIn(List<Date> values) {
            addCriterion("registertime not in", values, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeBetween(Date value1, Date value2) {
            addCriterion("registertime between", value1, value2, "registertime");
            return (Criteria) this;
        }

        public Criteria andRegistertimeNotBetween(Date value1, Date value2) {
            addCriterion("registertime not between", value1, value2, "registertime");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andCloseserviceidIsNull() {
            addCriterion("closeserviceid is null");
            return (Criteria) this;
        }

        public Criteria andCloseserviceidIsNotNull() {
            addCriterion("closeserviceid is not null");
            return (Criteria) this;
        }

        public Criteria andCloseserviceidEqualTo(Integer value) {
            addCriterion("closeserviceid =", value, "closeserviceid");
            return (Criteria) this;
        }

        public Criteria andCloseserviceidNotEqualTo(Integer value) {
            addCriterion("closeserviceid <>", value, "closeserviceid");
            return (Criteria) this;
        }

        public Criteria andCloseserviceidGreaterThan(Integer value) {
            addCriterion("closeserviceid >", value, "closeserviceid");
            return (Criteria) this;
        }

        public Criteria andCloseserviceidGreaterThanOrEqualTo(Integer value) {
            addCriterion("closeserviceid >=", value, "closeserviceid");
            return (Criteria) this;
        }

        public Criteria andCloseserviceidLessThan(Integer value) {
            addCriterion("closeserviceid <", value, "closeserviceid");
            return (Criteria) this;
        }

        public Criteria andCloseserviceidLessThanOrEqualTo(Integer value) {
            addCriterion("closeserviceid <=", value, "closeserviceid");
            return (Criteria) this;
        }

        public Criteria andCloseserviceidIn(List<Integer> values) {
            addCriterion("closeserviceid in", values, "closeserviceid");
            return (Criteria) this;
        }

        public Criteria andCloseserviceidNotIn(List<Integer> values) {
            addCriterion("closeserviceid not in", values, "closeserviceid");
            return (Criteria) this;
        }

        public Criteria andCloseserviceidBetween(Integer value1, Integer value2) {
            addCriterion("closeserviceid between", value1, value2, "closeserviceid");
            return (Criteria) this;
        }

        public Criteria andCloseserviceidNotBetween(Integer value1, Integer value2) {
            addCriterion("closeserviceid not between", value1, value2, "closeserviceid");
            return (Criteria) this;
        }

        public Criteria andOpenfileIsNull() {
            addCriterion("openfile is null");
            return (Criteria) this;
        }

        public Criteria andOpenfileIsNotNull() {
            addCriterion("openfile is not null");
            return (Criteria) this;
        }

        public Criteria andOpenfileEqualTo(String value) {
            addCriterion("openfile =", value, "openfile");
            return (Criteria) this;
        }

        public Criteria andOpenfileNotEqualTo(String value) {
            addCriterion("openfile <>", value, "openfile");
            return (Criteria) this;
        }

        public Criteria andOpenfileGreaterThan(String value) {
            addCriterion("openfile >", value, "openfile");
            return (Criteria) this;
        }

        public Criteria andOpenfileGreaterThanOrEqualTo(String value) {
            addCriterion("openfile >=", value, "openfile");
            return (Criteria) this;
        }

        public Criteria andOpenfileLessThan(String value) {
            addCriterion("openfile <", value, "openfile");
            return (Criteria) this;
        }

        public Criteria andOpenfileLessThanOrEqualTo(String value) {
            addCriterion("openfile <=", value, "openfile");
            return (Criteria) this;
        }

        public Criteria andOpenfileLike(String value) {
            addCriterion("openfile like", value, "openfile");
            return (Criteria) this;
        }

        public Criteria andOpenfileNotLike(String value) {
            addCriterion("openfile not like", value, "openfile");
            return (Criteria) this;
        }

        public Criteria andOpenfileIn(List<String> values) {
            addCriterion("openfile in", values, "openfile");
            return (Criteria) this;
        }

        public Criteria andOpenfileNotIn(List<String> values) {
            addCriterion("openfile not in", values, "openfile");
            return (Criteria) this;
        }

        public Criteria andOpenfileBetween(String value1, String value2) {
            addCriterion("openfile between", value1, value2, "openfile");
            return (Criteria) this;
        }

        public Criteria andOpenfileNotBetween(String value1, String value2) {
            addCriterion("openfile not between", value1, value2, "openfile");
            return (Criteria) this;
        }

        public Criteria andOpenfilenumberIsNull() {
            addCriterion("openfilenumber is null");
            return (Criteria) this;
        }

        public Criteria andOpenfilenumberIsNotNull() {
            addCriterion("openfilenumber is not null");
            return (Criteria) this;
        }

        public Criteria andOpenfilenumberEqualTo(String value) {
            addCriterion("openfilenumber =", value, "openfilenumber");
            return (Criteria) this;
        }

        public Criteria andOpenfilenumberNotEqualTo(String value) {
            addCriterion("openfilenumber <>", value, "openfilenumber");
            return (Criteria) this;
        }

        public Criteria andOpenfilenumberGreaterThan(String value) {
            addCriterion("openfilenumber >", value, "openfilenumber");
            return (Criteria) this;
        }

        public Criteria andOpenfilenumberGreaterThanOrEqualTo(String value) {
            addCriterion("openfilenumber >=", value, "openfilenumber");
            return (Criteria) this;
        }

        public Criteria andOpenfilenumberLessThan(String value) {
            addCriterion("openfilenumber <", value, "openfilenumber");
            return (Criteria) this;
        }

        public Criteria andOpenfilenumberLessThanOrEqualTo(String value) {
            addCriterion("openfilenumber <=", value, "openfilenumber");
            return (Criteria) this;
        }

        public Criteria andOpenfilenumberLike(String value) {
            addCriterion("openfilenumber like", value, "openfilenumber");
            return (Criteria) this;
        }

        public Criteria andOpenfilenumberNotLike(String value) {
            addCriterion("openfilenumber not like", value, "openfilenumber");
            return (Criteria) this;
        }

        public Criteria andOpenfilenumberIn(List<String> values) {
            addCriterion("openfilenumber in", values, "openfilenumber");
            return (Criteria) this;
        }

        public Criteria andOpenfilenumberNotIn(List<String> values) {
            addCriterion("openfilenumber not in", values, "openfilenumber");
            return (Criteria) this;
        }

        public Criteria andOpenfilenumberBetween(String value1, String value2) {
            addCriterion("openfilenumber between", value1, value2, "openfilenumber");
            return (Criteria) this;
        }

        public Criteria andOpenfilenumberNotBetween(String value1, String value2) {
            addCriterion("openfilenumber not between", value1, value2, "openfilenumber");
            return (Criteria) this;
        }

        public Criteria andOpentimeIsNull() {
            addCriterion("opentime is null");
            return (Criteria) this;
        }

        public Criteria andOpentimeIsNotNull() {
            addCriterion("opentime is not null");
            return (Criteria) this;
        }

        public Criteria andOpentimeEqualTo(Date value) {
            addCriterion("opentime =", value, "opentime");
            return (Criteria) this;
        }

        public Criteria andOpentimeNotEqualTo(Date value) {
            addCriterion("opentime <>", value, "opentime");
            return (Criteria) this;
        }

        public Criteria andOpentimeGreaterThan(Date value) {
            addCriterion("opentime >", value, "opentime");
            return (Criteria) this;
        }

        public Criteria andOpentimeGreaterThanOrEqualTo(Date value) {
            addCriterion("opentime >=", value, "opentime");
            return (Criteria) this;
        }

        public Criteria andOpentimeLessThan(Date value) {
            addCriterion("opentime <", value, "opentime");
            return (Criteria) this;
        }

        public Criteria andOpentimeLessThanOrEqualTo(Date value) {
            addCriterion("opentime <=", value, "opentime");
            return (Criteria) this;
        }

        public Criteria andOpentimeIn(List<Date> values) {
            addCriterion("opentime in", values, "opentime");
            return (Criteria) this;
        }

        public Criteria andOpentimeNotIn(List<Date> values) {
            addCriterion("opentime not in", values, "opentime");
            return (Criteria) this;
        }

        public Criteria andOpentimeBetween(Date value1, Date value2) {
            addCriterion("opentime between", value1, value2, "opentime");
            return (Criteria) this;
        }

        public Criteria andOpentimeNotBetween(Date value1, Date value2) {
            addCriterion("opentime not between", value1, value2, "opentime");
            return (Criteria) this;
        }

        public Criteria andOpenregistertimeIsNull() {
            addCriterion("openregistertime is null");
            return (Criteria) this;
        }

        public Criteria andOpenregistertimeIsNotNull() {
            addCriterion("openregistertime is not null");
            return (Criteria) this;
        }

        public Criteria andOpenregistertimeEqualTo(Date value) {
            addCriterion("openregistertime =", value, "openregistertime");
            return (Criteria) this;
        }

        public Criteria andOpenregistertimeNotEqualTo(Date value) {
            addCriterion("openregistertime <>", value, "openregistertime");
            return (Criteria) this;
        }

        public Criteria andOpenregistertimeGreaterThan(Date value) {
            addCriterion("openregistertime >", value, "openregistertime");
            return (Criteria) this;
        }

        public Criteria andOpenregistertimeGreaterThanOrEqualTo(Date value) {
            addCriterion("openregistertime >=", value, "openregistertime");
            return (Criteria) this;
        }

        public Criteria andOpenregistertimeLessThan(Date value) {
            addCriterion("openregistertime <", value, "openregistertime");
            return (Criteria) this;
        }

        public Criteria andOpenregistertimeLessThanOrEqualTo(Date value) {
            addCriterion("openregistertime <=", value, "openregistertime");
            return (Criteria) this;
        }

        public Criteria andOpenregistertimeIn(List<Date> values) {
            addCriterion("openregistertime in", values, "openregistertime");
            return (Criteria) this;
        }

        public Criteria andOpenregistertimeNotIn(List<Date> values) {
            addCriterion("openregistertime not in", values, "openregistertime");
            return (Criteria) this;
        }

        public Criteria andOpenregistertimeBetween(Date value1, Date value2) {
            addCriterion("openregistertime between", value1, value2, "openregistertime");
            return (Criteria) this;
        }

        public Criteria andOpenregistertimeNotBetween(Date value1, Date value2) {
            addCriterion("openregistertime not between", value1, value2, "openregistertime");
            return (Criteria) this;
        }

        public Criteria andOpenuidIsNull() {
            addCriterion("openuid is null");
            return (Criteria) this;
        }

        public Criteria andOpenuidIsNotNull() {
            addCriterion("openuid is not null");
            return (Criteria) this;
        }

        public Criteria andOpenuidEqualTo(Integer value) {
            addCriterion("openuid =", value, "openuid");
            return (Criteria) this;
        }

        public Criteria andOpenuidNotEqualTo(Integer value) {
            addCriterion("openuid <>", value, "openuid");
            return (Criteria) this;
        }

        public Criteria andOpenuidGreaterThan(Integer value) {
            addCriterion("openuid >", value, "openuid");
            return (Criteria) this;
        }

        public Criteria andOpenuidGreaterThanOrEqualTo(Integer value) {
            addCriterion("openuid >=", value, "openuid");
            return (Criteria) this;
        }

        public Criteria andOpenuidLessThan(Integer value) {
            addCriterion("openuid <", value, "openuid");
            return (Criteria) this;
        }

        public Criteria andOpenuidLessThanOrEqualTo(Integer value) {
            addCriterion("openuid <=", value, "openuid");
            return (Criteria) this;
        }

        public Criteria andOpenuidIn(List<Integer> values) {
            addCriterion("openuid in", values, "openuid");
            return (Criteria) this;
        }

        public Criteria andOpenuidNotIn(List<Integer> values) {
            addCriterion("openuid not in", values, "openuid");
            return (Criteria) this;
        }

        public Criteria andOpenuidBetween(Integer value1, Integer value2) {
            addCriterion("openuid between", value1, value2, "openuid");
            return (Criteria) this;
        }

        public Criteria andOpenuidNotBetween(Integer value1, Integer value2) {
            addCriterion("openuid not between", value1, value2, "openuid");
            return (Criteria) this;
        }

        public Criteria andDescriptIsNull() {
            addCriterion("descript is null");
            return (Criteria) this;
        }

        public Criteria andDescriptIsNotNull() {
            addCriterion("descript is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptEqualTo(String value) {
            addCriterion("descript =", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptNotEqualTo(String value) {
            addCriterion("descript <>", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptGreaterThan(String value) {
            addCriterion("descript >", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptGreaterThanOrEqualTo(String value) {
            addCriterion("descript >=", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptLessThan(String value) {
            addCriterion("descript <", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptLessThanOrEqualTo(String value) {
            addCriterion("descript <=", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptLike(String value) {
            addCriterion("descript like", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptNotLike(String value) {
            addCriterion("descript not like", value, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptIn(List<String> values) {
            addCriterion("descript in", values, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptNotIn(List<String> values) {
            addCriterion("descript not in", values, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptBetween(String value1, String value2) {
            addCriterion("descript between", value1, value2, "descript");
            return (Criteria) this;
        }

        public Criteria andDescriptNotBetween(String value1, String value2) {
            addCriterion("descript not between", value1, value2, "descript");
            return (Criteria) this;
        }

        public Criteria andRoomidIsNull() {
            addCriterion("roomid is null");
            return (Criteria) this;
        }

        public Criteria andRoomidIsNotNull() {
            addCriterion("roomid is not null");
            return (Criteria) this;
        }

        public Criteria andRoomidEqualTo(Integer value) {
            addCriterion("roomid =", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidNotEqualTo(Integer value) {
            addCriterion("roomid <>", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidGreaterThan(Integer value) {
            addCriterion("roomid >", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidGreaterThanOrEqualTo(Integer value) {
            addCriterion("roomid >=", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidLessThan(Integer value) {
            addCriterion("roomid <", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidLessThanOrEqualTo(Integer value) {
            addCriterion("roomid <=", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidIn(List<Integer> values) {
            addCriterion("roomid in", values, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidNotIn(List<Integer> values) {
            addCriterion("roomid not in", values, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidBetween(Integer value1, Integer value2) {
            addCriterion("roomid between", value1, value2, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidNotBetween(Integer value1, Integer value2) {
            addCriterion("roomid not between", value1, value2, "roomid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table closeregistration
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 22 18:58:51 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table closeregistration
     *
     * @mbggenerated Thu Aug 22 18:58:51 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}