package com.woniu.entity;

import java.util.Date;

public class Closeregistration {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeregistration.id
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeregistration.serviceid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer serviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeregistration.closeofficeid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer closeofficeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeregistration.closefile
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private String closefile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeregistration.closefilenumber
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private String closefilenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeregistration.closetime
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Date closetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeregistration.closedate
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Date closedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeregistration.registertime
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Date registertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeregistration.uid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeregistration.closeserviceid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer closeserviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeregistration.openfile
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private String openfile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeregistration.openfilenumber
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private String openfilenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeregistration.opentime
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Date opentime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeregistration.openregistertime
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Date openregistertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeregistration.openuid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer openuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column closeregistration.descript
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private String descript;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeregistration.id
     *
     * @return the value of closeregistration.id
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeregistration.id
     *
     * @param id the value for closeregistration.id
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeregistration.serviceid
     *
     * @return the value of closeregistration.serviceid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getServiceid() {
        return serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeregistration.serviceid
     *
     * @param serviceid the value for closeregistration.serviceid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setServiceid(Integer serviceid) {
        this.serviceid = serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeregistration.closeofficeid
     *
     * @return the value of closeregistration.closeofficeid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getCloseofficeid() {
        return closeofficeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeregistration.closeofficeid
     *
     * @param closeofficeid the value for closeregistration.closeofficeid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setCloseofficeid(Integer closeofficeid) {
        this.closeofficeid = closeofficeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeregistration.closefile
     *
     * @return the value of closeregistration.closefile
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public String getClosefile() {
        return closefile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeregistration.closefile
     *
     * @param closefile the value for closeregistration.closefile
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setClosefile(String closefile) {
        this.closefile = closefile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeregistration.closefilenumber
     *
     * @return the value of closeregistration.closefilenumber
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public String getClosefilenumber() {
        return closefilenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeregistration.closefilenumber
     *
     * @param closefilenumber the value for closeregistration.closefilenumber
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setClosefilenumber(String closefilenumber) {
        this.closefilenumber = closefilenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeregistration.closetime
     *
     * @return the value of closeregistration.closetime
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Date getClosetime() {
        return closetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeregistration.closetime
     *
     * @param closetime the value for closeregistration.closetime
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setClosetime(Date closetime) {
        this.closetime = closetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeregistration.closedate
     *
     * @return the value of closeregistration.closedate
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Date getClosedate() {
        return closedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeregistration.closedate
     *
     * @param closedate the value for closeregistration.closedate
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setClosedate(Date closedate) {
        this.closedate = closedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeregistration.registertime
     *
     * @return the value of closeregistration.registertime
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeregistration.registertime
     *
     * @param registertime the value for closeregistration.registertime
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeregistration.uid
     *
     * @return the value of closeregistration.uid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeregistration.uid
     *
     * @param uid the value for closeregistration.uid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeregistration.closeserviceid
     *
     * @return the value of closeregistration.closeserviceid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getCloseserviceid() {
        return closeserviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeregistration.closeserviceid
     *
     * @param closeserviceid the value for closeregistration.closeserviceid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setCloseserviceid(Integer closeserviceid) {
        this.closeserviceid = closeserviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeregistration.openfile
     *
     * @return the value of closeregistration.openfile
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public String getOpenfile() {
        return openfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeregistration.openfile
     *
     * @param openfile the value for closeregistration.openfile
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setOpenfile(String openfile) {
        this.openfile = openfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeregistration.openfilenumber
     *
     * @return the value of closeregistration.openfilenumber
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public String getOpenfilenumber() {
        return openfilenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeregistration.openfilenumber
     *
     * @param openfilenumber the value for closeregistration.openfilenumber
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setOpenfilenumber(String openfilenumber) {
        this.openfilenumber = openfilenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeregistration.opentime
     *
     * @return the value of closeregistration.opentime
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Date getOpentime() {
        return opentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeregistration.opentime
     *
     * @param opentime the value for closeregistration.opentime
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setOpentime(Date opentime) {
        this.opentime = opentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeregistration.openregistertime
     *
     * @return the value of closeregistration.openregistertime
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Date getOpenregistertime() {
        return openregistertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeregistration.openregistertime
     *
     * @param openregistertime the value for closeregistration.openregistertime
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setOpenregistertime(Date openregistertime) {
        this.openregistertime = openregistertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeregistration.openuid
     *
     * @return the value of closeregistration.openuid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getOpenuid() {
        return openuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeregistration.openuid
     *
     * @param openuid the value for closeregistration.openuid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setOpenuid(Integer openuid) {
        this.openuid = openuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column closeregistration.descript
     *
     * @return the value of closeregistration.descript
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public String getDescript() {
        return descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column closeregistration.descript
     *
     * @param descript the value for closeregistration.descript
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setDescript(String descript) {
        this.descript = descript;
    }
}