package com.woniu.entity;

public class Closeoffice {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column closeoffice.closeofficeid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer closeofficeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column closeoffice.closeoffice
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private String closeoffice;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column closeoffice.closeofficeid
	 * @return  the value of closeoffice.closeofficeid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getCloseofficeid() {
		return closeofficeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column closeoffice.closeofficeid
	 * @param closeofficeid  the value for closeoffice.closeofficeid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setCloseofficeid(Integer closeofficeid) {
		this.closeofficeid = closeofficeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column closeoffice.closeoffice
	 * @return  the value of closeoffice.closeoffice
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public String getCloseoffice() {
		return closeoffice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column closeoffice.closeoffice
	 * @param closeoffice  the value for closeoffice.closeoffice
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setCloseoffice(String closeoffice) {
		this.closeoffice = closeoffice;
	}
}