package com.woniu.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Existmortgage {
	
	private Userinfo userinfo;
	
	
	public Userinfo getUserinfo() {
		return userinfo;
	}

	public void setUserinfo(Userinfo userinfo) {
		this.userinfo = userinfo;
	}

	private Service service;
	

	public Service getService() {
		return service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column existmortgage.emid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer emid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column existmortgage.serviceid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer serviceid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column existmortgage.generalmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private BigDecimal generalmortgage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column existmortgage.maxmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private BigDecimal maxmortgage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column existmortgage.mortgagee
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer mortgagee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column existmortgage.mortgager
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer mortgager;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column existmortgage.debtor
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer debtor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column existmortgage.maxclaim
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private BigDecimal maxclaim;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column existmortgage.scope
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private String scope;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column existmortgage.returntime
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Date returntime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column existmortgage.registertime
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Date registertime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column existmortgage.uid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column existmortgage.descript
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private String descript;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column existmortgage.roomid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer roomid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column existmortgage.cancelserviceid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer cancelserviceid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column existmortgage.emid
	 * @return  the value of existmortgage.emid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getEmid() {
		return emid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column existmortgage.emid
	 * @param emid  the value for existmortgage.emid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setEmid(Integer emid) {
		this.emid = emid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column existmortgage.serviceid
	 * @return  the value of existmortgage.serviceid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getServiceid() {
		return serviceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column existmortgage.serviceid
	 * @param serviceid  the value for existmortgage.serviceid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setServiceid(Integer serviceid) {
		this.serviceid = serviceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column existmortgage.generalmortgage
	 * @return  the value of existmortgage.generalmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public BigDecimal getGeneralmortgage() {
		return generalmortgage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column existmortgage.generalmortgage
	 * @param generalmortgage  the value for existmortgage.generalmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setGeneralmortgage(BigDecimal generalmortgage) {
		this.generalmortgage = generalmortgage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column existmortgage.maxmortgage
	 * @return  the value of existmortgage.maxmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public BigDecimal getMaxmortgage() {
		return maxmortgage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column existmortgage.maxmortgage
	 * @param maxmortgage  the value for existmortgage.maxmortgage
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setMaxmortgage(BigDecimal maxmortgage) {
		this.maxmortgage = maxmortgage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column existmortgage.mortgagee
	 * @return  the value of existmortgage.mortgagee
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getMortgagee() {
		return mortgagee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column existmortgage.mortgagee
	 * @param mortgagee  the value for existmortgage.mortgagee
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setMortgagee(Integer mortgagee) {
		this.mortgagee = mortgagee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column existmortgage.mortgager
	 * @return  the value of existmortgage.mortgager
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getMortgager() {
		return mortgager;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column existmortgage.mortgager
	 * @param mortgager  the value for existmortgage.mortgager
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setMortgager(Integer mortgager) {
		this.mortgager = mortgager;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column existmortgage.debtor
	 * @return  the value of existmortgage.debtor
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getDebtor() {
		return debtor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column existmortgage.debtor
	 * @param debtor  the value for existmortgage.debtor
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setDebtor(Integer debtor) {
		this.debtor = debtor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column existmortgage.maxclaim
	 * @return  the value of existmortgage.maxclaim
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public BigDecimal getMaxclaim() {
		return maxclaim;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column existmortgage.maxclaim
	 * @param maxclaim  the value for existmortgage.maxclaim
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setMaxclaim(BigDecimal maxclaim) {
		this.maxclaim = maxclaim;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column existmortgage.scope
	 * @return  the value of existmortgage.scope
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public String getScope() {
		return scope;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column existmortgage.scope
	 * @param scope  the value for existmortgage.scope
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setScope(String scope) {
		this.scope = scope;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column existmortgage.returntime
	 * @return  the value of existmortgage.returntime
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Date getReturntime() {
		return returntime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column existmortgage.returntime
	 * @param returntime  the value for existmortgage.returntime
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setReturntime(Date returntime) {
		this.returntime = returntime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column existmortgage.registertime
	 * @return  the value of existmortgage.registertime
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Date getRegistertime() {
		return registertime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column existmortgage.registertime
	 * @param registertime  the value for existmortgage.registertime
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setRegistertime(Date registertime) {
		this.registertime = registertime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column existmortgage.uid
	 * @return  the value of existmortgage.uid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column existmortgage.uid
	 * @param uid  the value for existmortgage.uid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column existmortgage.descript
	 * @return  the value of existmortgage.descript
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public String getDescript() {
		return descript;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column existmortgage.descript
	 * @param descript  the value for existmortgage.descript
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setDescript(String descript) {
		this.descript = descript;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column existmortgage.roomid
	 * @return  the value of existmortgage.roomid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getRoomid() {
		return roomid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column existmortgage.roomid
	 * @param roomid  the value for existmortgage.roomid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setRoomid(Integer roomid) {
		this.roomid = roomid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column existmortgage.cancelserviceid
	 * @return  the value of existmortgage.cancelserviceid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getCancelserviceid() {
		return cancelserviceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column existmortgage.cancelserviceid
	 * @param cancelserviceid  the value for existmortgage.cancelserviceid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setCancelserviceid(Integer cancelserviceid) {
		this.cancelserviceid = cancelserviceid;
	}
}