package com.woniu.entity;

public class Gainingmethod {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gainingmethod.gid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer gid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gainingmethod.gname
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private String gname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gainingmethod.gid
	 * @return  the value of gainingmethod.gid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getGid() {
		return gid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gainingmethod.gid
	 * @param gid  the value for gainingmethod.gid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setGid(Integer gid) {
		this.gid = gid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gainingmethod.gname
	 * @return  the value of gainingmethod.gname
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public String getGname() {
		return gname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gainingmethod.gname
	 * @param gname  the value for gainingmethod.gname
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setGname(String gname) {
		this.gname = gname;
	}
}