package com.woniu.entity;

public class Landownership {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column landownership.oid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer oid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column landownership.oname
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private String oname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column landownership.oid
	 * @return  the value of landownership.oid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getOid() {
		return oid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column landownership.oid
	 * @param oid  the value for landownership.oid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setOid(Integer oid) {
		this.oid = oid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column landownership.oname
	 * @return  the value of landownership.oname
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public String getOname() {
		return oname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column landownership.oname
	 * @param oname  the value for landownership.oname
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setOname(String oname) {
		this.oname = oname;
	}
}