package com.woniu.entity;

public class Landuse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column landuse.lid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer lid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column landuse.lname
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private String lname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column landuse.lid
     *
     * @return the value of landuse.lid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column landuse.lid
     *
     * @param lid the value for landuse.lid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setLid(Integer lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column landuse.lname
     *
     * @return the value of landuse.lname
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public String getLname() {
        return lname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column landuse.lname
     *
     * @param lname the value for landuse.lname
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setLname(String lname) {
        this.lname = lname;
    }
}