package com.woniu.entity;

public class Landnumber {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column landnumber.lnid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer lnid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column landnumber.lnname
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private String lnname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column landnumber.bid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer bid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column landnumber.lnid
	 * @return  the value of landnumber.lnid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getLnid() {
		return lnid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column landnumber.lnid
	 * @param lnid  the value for landnumber.lnid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setLnid(Integer lnid) {
		this.lnid = lnid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column landnumber.lnname
	 * @return  the value of landnumber.lnname
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public String getLnname() {
		return lnname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column landnumber.lnname
	 * @param lnname  the value for landnumber.lnname
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setLnname(String lnname) {
		this.lnname = lnname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column landnumber.bid
	 * @return  the value of landnumber.bid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getBid() {
		return bid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column landnumber.bid
	 * @param bid  the value for landnumber.bid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setBid(Integer bid) {
		this.bid = bid;
	}
}