package com.woniu.entity;

import java.io.Serializable;
import java.util.Date;

public class Log implements Serializable{
    /**   
	 * @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么)   
	 */ 
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.logid
     *
     * @mbggenerated Tue Aug 06 10:19:50 CST 2019
     */
    private Integer logid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.uid
     *
     * @mbggenerated Tue Aug 06 10:19:50 CST 2019
     */
    private Integer uid;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.action
     *
     * @mbggenerated Tue Aug 06 10:19:50 CST 2019
     */
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.actiontime
     *
     * @mbggenerated Tue Aug 06 10:19:50 CST 2019
     */
    private Date actiontime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.uname
     *
     * @mbggenerated Tue Aug 06 10:19:50 CST 2019
     */
    private String uname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.logid
     *
     * @return the value of log.logid
     *
     * @mbggenerated Tue Aug 06 10:19:50 CST 2019
     */
    public Integer getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.logid
     *
     * @param logid the value for log.logid
     *
     * @mbggenerated Tue Aug 06 10:19:50 CST 2019
     */
    public void setLogid(Integer logid) {
        this.logid = logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.uid
     *
     * @return the value of log.uid
     *
     * @mbggenerated Tue Aug 06 10:19:50 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.uid
     *
     * @param uid the value for log.uid
     *
     * @mbggenerated Tue Aug 06 10:19:50 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.action
     *
     * @return the value of log.action
     *
     * @mbggenerated Tue Aug 06 10:19:50 CST 2019
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.action
     *
     * @param action the value for log.action
     *
     * @mbggenerated Tue Aug 06 10:19:50 CST 2019
     */
    public void setAction(String action) {
        this.action = action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.actiontime
     *
     * @return the value of log.actiontime
     *
     * @mbggenerated Tue Aug 06 10:19:50 CST 2019
     */
    public Date getActiontime() {
        return actiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.actiontime
     *
     * @param actiontime the value for log.actiontime
     *
     * @mbggenerated Tue Aug 06 10:19:50 CST 2019
     */
    public void setActiontime(Date actiontime) {
        this.actiontime = actiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.uname
     *
     * @return the value of log.uname
     *
     * @mbggenerated Tue Aug 06 10:19:50 CST 2019
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.uname
     *
     * @param uname the value for log.uname
     *
     * @mbggenerated Tue Aug 06 10:19:50 CST 2019
     */
    public void setUname(String uname) {
        this.uname = uname;
    }
}