package com.woniu.entity;

import java.util.Date;

public class Netsign {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column netsign.netid
	 * @mbg.generated  Tue Aug 20 18:39:04 CST 2019
	 */
	private Integer netid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column netsign.netnumber
	 * @mbg.generated  Tue Aug 20 18:39:04 CST 2019
	 */
	private String netnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column netsign.roomid
	 * @mbg.generated  Tue Aug 20 18:39:04 CST 2019
	 */
	private Integer roomid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column netsign.buyer
	 * @mbg.generated  Tue Aug 20 18:39:04 CST 2019
	 */
	private Integer buyer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column netsign.seller
	 * @mbg.generated  Tue Aug 20 18:39:04 CST 2019
	 */
	private Integer seller;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column netsign.netstatus
	 * @mbg.generated  Tue Aug 20 18:39:04 CST 2019
	 */
	private Boolean netstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column netsign.nettime
	 * @mbg.generated  Tue Aug 20 18:39:04 CST 2019
	 */
	private Date nettime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column netsign.netid
	 * @return  the value of netsign.netid
	 * @mbg.generated  Tue Aug 20 18:39:04 CST 2019
	 */
	public Integer getNetid() {
		return netid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column netsign.netid
	 * @param netid  the value for netsign.netid
	 * @mbg.generated  Tue Aug 20 18:39:04 CST 2019
	 */
	public void setNetid(Integer netid) {
		this.netid = netid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column netsign.netnumber
	 * @return  the value of netsign.netnumber
	 * @mbg.generated  Tue Aug 20 18:39:04 CST 2019
	 */
	public String getNetnumber() {
		return netnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column netsign.netnumber
	 * @param netnumber  the value for netsign.netnumber
	 * @mbg.generated  Tue Aug 20 18:39:04 CST 2019
	 */
	public void setNetnumber(String netnumber) {
		this.netnumber = netnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column netsign.roomid
	 * @return  the value of netsign.roomid
	 * @mbg.generated  Tue Aug 20 18:39:04 CST 2019
	 */
	public Integer getRoomid() {
		return roomid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column netsign.roomid
	 * @param roomid  the value for netsign.roomid
	 * @mbg.generated  Tue Aug 20 18:39:04 CST 2019
	 */
	public void setRoomid(Integer roomid) {
		this.roomid = roomid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column netsign.buyer
	 * @return  the value of netsign.buyer
	 * @mbg.generated  Tue Aug 20 18:39:04 CST 2019
	 */
	public Integer getBuyer() {
		return buyer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column netsign.buyer
	 * @param buyer  the value for netsign.buyer
	 * @mbg.generated  Tue Aug 20 18:39:04 CST 2019
	 */
	public void setBuyer(Integer buyer) {
		this.buyer = buyer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column netsign.seller
	 * @return  the value of netsign.seller
	 * @mbg.generated  Tue Aug 20 18:39:04 CST 2019
	 */
	public Integer getSeller() {
		return seller;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column netsign.seller
	 * @param seller  the value for netsign.seller
	 * @mbg.generated  Tue Aug 20 18:39:04 CST 2019
	 */
	public void setSeller(Integer seller) {
		this.seller = seller;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column netsign.netstatus
	 * @return  the value of netsign.netstatus
	 * @mbg.generated  Tue Aug 20 18:39:04 CST 2019
	 */
	public Boolean getNetstatus() {
		return netstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column netsign.netstatus
	 * @param netstatus  the value for netsign.netstatus
	 * @mbg.generated  Tue Aug 20 18:39:04 CST 2019
	 */
	public void setNetstatus(Boolean netstatus) {
		this.netstatus = netstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column netsign.nettime
	 * @return  the value of netsign.nettime
	 * @mbg.generated  Tue Aug 20 18:39:04 CST 2019
	 */
	public Date getNettime() {
		return nettime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column netsign.nettime
	 * @param nettime  the value for netsign.nettime
	 * @mbg.generated  Tue Aug 20 18:39:04 CST 2019
	 */
	public void setNettime(Date nettime) {
		this.nettime = nettime;
	}
}