package com.woniu.entity;

import java.util.Date;

public class Otherregistration {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherregistration.id
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherregistration.serviceid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer serviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherregistration.registrationtypeid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer registrationtypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherregistration.obligee
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer obligee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherregistration.boligeenumber
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private String boligeenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherregistration.obligor
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer obligor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherregistration.obligornumber
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private String obligornumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherregistration.prevregisternumber
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private String prevregisternumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherregistration.registertime
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Date registertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherregistration.uid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherregistration.prevserviceid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer prevserviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherregistration.descript
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private String descript;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherregistration.roomid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer roomid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherregistration.id
     *
     * @return the value of otherregistration.id
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherregistration.id
     *
     * @param id the value for otherregistration.id
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherregistration.serviceid
     *
     * @return the value of otherregistration.serviceid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getServiceid() {
        return serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherregistration.serviceid
     *
     * @param serviceid the value for otherregistration.serviceid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setServiceid(Integer serviceid) {
        this.serviceid = serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherregistration.registrationtypeid
     *
     * @return the value of otherregistration.registrationtypeid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getRegistrationtypeid() {
        return registrationtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherregistration.registrationtypeid
     *
     * @param registrationtypeid the value for otherregistration.registrationtypeid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setRegistrationtypeid(Integer registrationtypeid) {
        this.registrationtypeid = registrationtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherregistration.obligee
     *
     * @return the value of otherregistration.obligee
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getObligee() {
        return obligee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherregistration.obligee
     *
     * @param obligee the value for otherregistration.obligee
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setObligee(Integer obligee) {
        this.obligee = obligee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherregistration.boligeenumber
     *
     * @return the value of otherregistration.boligeenumber
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public String getBoligeenumber() {
        return boligeenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherregistration.boligeenumber
     *
     * @param boligeenumber the value for otherregistration.boligeenumber
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setBoligeenumber(String boligeenumber) {
        this.boligeenumber = boligeenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherregistration.obligor
     *
     * @return the value of otherregistration.obligor
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getObligor() {
        return obligor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherregistration.obligor
     *
     * @param obligor the value for otherregistration.obligor
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setObligor(Integer obligor) {
        this.obligor = obligor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherregistration.obligornumber
     *
     * @return the value of otherregistration.obligornumber
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public String getObligornumber() {
        return obligornumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherregistration.obligornumber
     *
     * @param obligornumber the value for otherregistration.obligornumber
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setObligornumber(String obligornumber) {
        this.obligornumber = obligornumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherregistration.prevregisternumber
     *
     * @return the value of otherregistration.prevregisternumber
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public String getPrevregisternumber() {
        return prevregisternumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherregistration.prevregisternumber
     *
     * @param prevregisternumber the value for otherregistration.prevregisternumber
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setPrevregisternumber(String prevregisternumber) {
        this.prevregisternumber = prevregisternumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherregistration.registertime
     *
     * @return the value of otherregistration.registertime
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherregistration.registertime
     *
     * @param registertime the value for otherregistration.registertime
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherregistration.uid
     *
     * @return the value of otherregistration.uid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherregistration.uid
     *
     * @param uid the value for otherregistration.uid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherregistration.prevserviceid
     *
     * @return the value of otherregistration.prevserviceid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getPrevserviceid() {
        return prevserviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherregistration.prevserviceid
     *
     * @param prevserviceid the value for otherregistration.prevserviceid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setPrevserviceid(Integer prevserviceid) {
        this.prevserviceid = prevserviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherregistration.descript
     *
     * @return the value of otherregistration.descript
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public String getDescript() {
        return descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherregistration.descript
     *
     * @param descript the value for otherregistration.descript
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setDescript(String descript) {
        this.descript = descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherregistration.roomid
     *
     * @return the value of otherregistration.roomid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherregistration.roomid
     *
     * @param roomid the value for otherregistration.roomid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }
}