package com.woniu.entity;

import java.util.Date;

public class Ownership {
	private Room room;
	private Landnumber landnumber;
	private House house;
	private Building building;
	
	public Landnumber getLandnumber() {
		return landnumber;
	}

	public void setLandnumber(Landnumber landnumber) {
		this.landnumber = landnumber;
	}

	public House getHouse() {
		return house;
	}

	public void setHouse(House house) {
		this.house = house;
	}

	public Building getBuilding() {
		return building;
	}

	public void setBuilding(Building building) {
		this.building = building;
	}

	public Room getRoom() {
		return room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	private Userinfo userinfo;
	
	
	
	public Userinfo getUserinfo() {
		return userinfo;
	}

	public void setUserinfo(Userinfo userinfo) {
		this.userinfo = userinfo;
	}

	private Client client;
	
	public Client getClient() {
		return client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ownership.osid
	 * @mbg.generated  Wed Aug 21 14:57:48 CST 2019
	 */
	private Integer osid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ownership.servicenumber
	 * @mbg.generated  Wed Aug 21 14:57:48 CST 2019
	 */
	private String servicenumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ownership.roomid
	 * @mbg.generated  Wed Aug 21 14:57:48 CST 2019
	 */
	private Integer roomid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ownership.registertime
	 * @mbg.generated  Wed Aug 21 14:57:48 CST 2019
	 */
	private Date registertime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ownership.uid
	 * @mbg.generated  Wed Aug 21 14:57:48 CST 2019
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ownership.descript
	 * @mbg.generated  Wed Aug 21 14:57:48 CST 2019
	 */
	private String descript;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ownership.clientid
	 * @mbg.generated  Wed Aug 21 14:57:48 CST 2019
	 */
	private Integer clientid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ownership.osid
	 * @return  the value of ownership.osid
	 * @mbg.generated  Wed Aug 21 14:57:48 CST 2019
	 */
	public Integer getOsid() {
		return osid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ownership.osid
	 * @param osid  the value for ownership.osid
	 * @mbg.generated  Wed Aug 21 14:57:48 CST 2019
	 */
	public void setOsid(Integer osid) {
		this.osid = osid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ownership.servicenumber
	 * @return  the value of ownership.servicenumber
	 * @mbg.generated  Wed Aug 21 14:57:48 CST 2019
	 */
	public String getServicenumber() {
		return servicenumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ownership.servicenumber
	 * @param servicenumber  the value for ownership.servicenumber
	 * @mbg.generated  Wed Aug 21 14:57:48 CST 2019
	 */
	public void setServicenumber(String servicenumber) {
		this.servicenumber = servicenumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ownership.roomid
	 * @return  the value of ownership.roomid
	 * @mbg.generated  Wed Aug 21 14:57:48 CST 2019
	 */
	public Integer getRoomid() {
		return roomid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ownership.roomid
	 * @param roomid  the value for ownership.roomid
	 * @mbg.generated  Wed Aug 21 14:57:48 CST 2019
	 */
	public void setRoomid(Integer roomid) {
		this.roomid = roomid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ownership.registertime
	 * @return  the value of ownership.registertime
	 * @mbg.generated  Wed Aug 21 14:57:48 CST 2019
	 */
	public Date getRegistertime() {
		return registertime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ownership.registertime
	 * @param registertime  the value for ownership.registertime
	 * @mbg.generated  Wed Aug 21 14:57:48 CST 2019
	 */
	public void setRegistertime(Date registertime) {
		this.registertime = registertime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ownership.uid
	 * @return  the value of ownership.uid
	 * @mbg.generated  Wed Aug 21 14:57:48 CST 2019
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ownership.uid
	 * @param uid  the value for ownership.uid
	 * @mbg.generated  Wed Aug 21 14:57:48 CST 2019
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ownership.descript
	 * @return  the value of ownership.descript
	 * @mbg.generated  Wed Aug 21 14:57:48 CST 2019
	 */
	public String getDescript() {
		return descript;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ownership.descript
	 * @param descript  the value for ownership.descript
	 * @mbg.generated  Wed Aug 21 14:57:48 CST 2019
	 */
	public void setDescript(String descript) {
		this.descript = descript;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ownership.clientid
	 * @return  the value of ownership.clientid
	 * @mbg.generated  Wed Aug 21 14:57:48 CST 2019
	 */
	public Integer getClientid() {
		return clientid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ownership.clientid
	 * @param clientid  the value for ownership.clientid
	 * @mbg.generated  Wed Aug 21 14:57:48 CST 2019
	 */
	public void setClientid(Integer clientid) {
		this.clientid = clientid;
	}

	@Override
	public String toString() {
		return "Ownership [room=" + room + ", landnumber=" + landnumber + ", house=" + house + ", building=" + building
				+ ", userinfo=" + userinfo + ", client=" + client + ", osid=" + osid + ", servicenumber="
				+ servicenumber + ", roomid=" + roomid + ", registertime=" + registertime + ", uid=" + uid
				+ ", descript=" + descript + ", clientid=" + clientid + "]";
	}

	
}