package com.woniu.entity;

import java.io.Serializable;
import java.util.List;

public class Province implements Serializable{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column province.pid
	 * @mbg.generated  Mon Aug 19 15:45:31 CST 2019
	 */
	private Integer pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column province.pname
	 * @mbg.generated  Mon Aug 19 15:45:31 CST 2019
	 */
	private String pname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column province.pid
	 * @return  the value of province.pid
	 * @mbg.generated  Mon Aug 19 15:45:31 CST 2019
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column province.pid
	 * @param pid  the value for province.pid
	 * @mbg.generated  Mon Aug 19 15:45:31 CST 2019
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column province.pname
	 * @return  the value of province.pname
	 * @mbg.generated  Mon Aug 19 15:45:31 CST 2019
	 */
	public String getPname() {
		return pname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column province.pname
	 * @param pname  the value for province.pname
	 * @mbg.generated  Mon Aug 19 15:45:31 CST 2019
	 */
	public void setPname(String pname) {
		this.pname = pname;
	}

	/**   
	 * @Fields serialVersionUID : TODO(用一句话描述这个变量表示�?�?)   
	 */ 
	private static final long serialVersionUID = 1L;
	private List citys;

	public List getCitys() {
		return citys;
	}

	public void setCitys(List citys) {
		this.citys = citys;
	}
}