package com.woniu.entity;

public class Registertemporary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registertemporary.rtid
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private Integer rtid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registertemporary.proposer
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String proposer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registertemporary.domicileaddress
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String domicileaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registertemporary.proptel
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String proptel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registertemporary.propidcard
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String propidcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registertemporary.agent
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String agent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registertemporary.agentidcard
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String agentidcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registertemporary.zone
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String zone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registertemporary.buildingarea
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String buildingarea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registertemporary.registrationtypes
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String registrationtypes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registertemporary.roomtype
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String roomtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registertemporary.gainingmethod
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String gainingmethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registertemporary.roomaddress
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String roomaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registertemporary.application
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String application;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registertemporary.idcopy
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String idcopy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registertemporary.photo
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registertemporary.purchasecopy
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String purchasecopy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registertemporary.contractcopy
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String contractcopy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registertemporary.taxcopy
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String taxcopy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registertemporary.servicetypeid
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private Integer servicetypeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registertemporary.rtid
     *
     * @return the value of registertemporary.rtid
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public Integer getRtid() {
        return rtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registertemporary.rtid
     *
     * @param rtid the value for registertemporary.rtid
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setRtid(Integer rtid) {
        this.rtid = rtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registertemporary.proposer
     *
     * @return the value of registertemporary.proposer
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getProposer() {
        return proposer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registertemporary.proposer
     *
     * @param proposer the value for registertemporary.proposer
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setProposer(String proposer) {
        this.proposer = proposer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registertemporary.domicileaddress
     *
     * @return the value of registertemporary.domicileaddress
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getDomicileaddress() {
        return domicileaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registertemporary.domicileaddress
     *
     * @param domicileaddress the value for registertemporary.domicileaddress
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setDomicileaddress(String domicileaddress) {
        this.domicileaddress = domicileaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registertemporary.proptel
     *
     * @return the value of registertemporary.proptel
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getProptel() {
        return proptel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registertemporary.proptel
     *
     * @param proptel the value for registertemporary.proptel
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setProptel(String proptel) {
        this.proptel = proptel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registertemporary.propidcard
     *
     * @return the value of registertemporary.propidcard
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getPropidcard() {
        return propidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registertemporary.propidcard
     *
     * @param propidcard the value for registertemporary.propidcard
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setPropidcard(String propidcard) {
        this.propidcard = propidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registertemporary.agent
     *
     * @return the value of registertemporary.agent
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getAgent() {
        return agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registertemporary.agent
     *
     * @param agent the value for registertemporary.agent
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setAgent(String agent) {
        this.agent = agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registertemporary.agentidcard
     *
     * @return the value of registertemporary.agentidcard
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getAgentidcard() {
        return agentidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registertemporary.agentidcard
     *
     * @param agentidcard the value for registertemporary.agentidcard
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setAgentidcard(String agentidcard) {
        this.agentidcard = agentidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registertemporary.zone
     *
     * @return the value of registertemporary.zone
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getZone() {
        return zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registertemporary.zone
     *
     * @param zone the value for registertemporary.zone
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setZone(String zone) {
        this.zone = zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registertemporary.buildingarea
     *
     * @return the value of registertemporary.buildingarea
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getBuildingarea() {
        return buildingarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registertemporary.buildingarea
     *
     * @param buildingarea the value for registertemporary.buildingarea
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setBuildingarea(String buildingarea) {
        this.buildingarea = buildingarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registertemporary.registrationtypes
     *
     * @return the value of registertemporary.registrationtypes
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getRegistrationtypes() {
        return registrationtypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registertemporary.registrationtypes
     *
     * @param registrationtypes the value for registertemporary.registrationtypes
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setRegistrationtypes(String registrationtypes) {
        this.registrationtypes = registrationtypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registertemporary.roomtype
     *
     * @return the value of registertemporary.roomtype
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getRoomtype() {
        return roomtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registertemporary.roomtype
     *
     * @param roomtype the value for registertemporary.roomtype
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setRoomtype(String roomtype) {
        this.roomtype = roomtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registertemporary.gainingmethod
     *
     * @return the value of registertemporary.gainingmethod
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getGainingmethod() {
        return gainingmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registertemporary.gainingmethod
     *
     * @param gainingmethod the value for registertemporary.gainingmethod
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setGainingmethod(String gainingmethod) {
        this.gainingmethod = gainingmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registertemporary.roomaddress
     *
     * @return the value of registertemporary.roomaddress
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getRoomaddress() {
        return roomaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registertemporary.roomaddress
     *
     * @param roomaddress the value for registertemporary.roomaddress
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setRoomaddress(String roomaddress) {
        this.roomaddress = roomaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registertemporary.application
     *
     * @return the value of registertemporary.application
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getApplication() {
        return application;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registertemporary.application
     *
     * @param application the value for registertemporary.application
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setApplication(String application) {
        this.application = application;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registertemporary.idcopy
     *
     * @return the value of registertemporary.idcopy
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getIdcopy() {
        return idcopy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registertemporary.idcopy
     *
     * @param idcopy the value for registertemporary.idcopy
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setIdcopy(String idcopy) {
        this.idcopy = idcopy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registertemporary.photo
     *
     * @return the value of registertemporary.photo
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registertemporary.photo
     *
     * @param photo the value for registertemporary.photo
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registertemporary.purchasecopy
     *
     * @return the value of registertemporary.purchasecopy
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getPurchasecopy() {
        return purchasecopy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registertemporary.purchasecopy
     *
     * @param purchasecopy the value for registertemporary.purchasecopy
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setPurchasecopy(String purchasecopy) {
        this.purchasecopy = purchasecopy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registertemporary.contractcopy
     *
     * @return the value of registertemporary.contractcopy
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getContractcopy() {
        return contractcopy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registertemporary.contractcopy
     *
     * @param contractcopy the value for registertemporary.contractcopy
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setContractcopy(String contractcopy) {
        this.contractcopy = contractcopy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registertemporary.taxcopy
     *
     * @return the value of registertemporary.taxcopy
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getTaxcopy() {
        return taxcopy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registertemporary.taxcopy
     *
     * @param taxcopy the value for registertemporary.taxcopy
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setTaxcopy(String taxcopy) {
        this.taxcopy = taxcopy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registertemporary.servicetypeid
     *
     * @return the value of registertemporary.servicetypeid
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public Integer getServicetypeid() {
        return servicetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registertemporary.servicetypeid
     *
     * @param servicetypeid the value for registertemporary.servicetypeid
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setServicetypeid(Integer servicetypeid) {
        this.servicetypeid = servicetypeid;
    }
}