package com.woniu.entity;

public class Registrationtype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registrationtype.registrationtypeid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer registrationtypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registrationtype.registrationtype
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private String registrationtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registrationtype.registrationtypeid
     *
     * @return the value of registrationtype.registrationtypeid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getRegistrationtypeid() {
        return registrationtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registrationtype.registrationtypeid
     *
     * @param registrationtypeid the value for registrationtype.registrationtypeid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setRegistrationtypeid(Integer registrationtypeid) {
        this.registrationtypeid = registrationtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registrationtype.registrationtype
     *
     * @return the value of registrationtype.registrationtype
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public String getRegistrationtype() {
        return registrationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registrationtype.registrationtype
     *
     * @param registrationtype the value for registrationtype.registrationtype
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setRegistrationtype(String registrationtype) {
        this.registrationtype = registrationtype;
    }
}