package com.woniu.entity;

import java.util.ArrayList;
import java.util.List;

public class Room {
	
	private List<Dissentingregistration> dissentingregistrations=new ArrayList<Dissentingregistration>();
	private List<Closeregistration> closeregistrations=new ArrayList<Closeregistration>();
	
	
	 
	public List<Dissentingregistration> getDissentingregistrations() {
		return dissentingregistrations;
	}

	public void setDissentingregistrations(List<Dissentingregistration> dissentingregistrations) {
		this.dissentingregistrations = dissentingregistrations;
	}

	public List<Closeregistration> getCloseregistrations() {
		return closeregistrations;
	}

	public void setCloseregistrations(List<Closeregistration> closeregistrations) {
		this.closeregistrations = closeregistrations;
	}

	private List<Otherregistration> otherregistrations=new ArrayList<Otherregistration>();
	
	
	public List<Otherregistration> getOtherregistrations() {
		return otherregistrations;
	}

	public void setOtherregistrations(List<Otherregistration> otherregistrations) {
		this.otherregistrations = otherregistrations;
	}

	private List<Beinmortgage> beinmortgages=new ArrayList<Beinmortgage>();
	
	
	public List<Beinmortgage> getBeinmortgages() {
		return beinmortgages;
	}

	public void setBeinmortgages(List<Beinmortgage> beinmortgages) {
		this.beinmortgages = beinmortgages;
	}

	private List<Existmortgage> existmortgages=new ArrayList<Existmortgage>();
	
	
	
	public List<Existmortgage> getExistmortgages() {
		return existmortgages;
	}

	public void setExistmortgages(List<Existmortgage> existmortgages) {
		this.existmortgages = existmortgages;
	}

	private List<Ownership> ownerships=new ArrayList<Ownership>();
	
	

	public List<Ownership> getOwnerships() {
		return ownerships;
	}

	public void setOwnerships(List<Ownership> ownerships) {
		this.ownerships = ownerships;
	}

	private Building building;
	
	
	public Building getBuilding() {
		return building;
	}

	public void setBuilding(Building building) {
		this.building = building;
	}

	private Roomstatus roomstatus;
	
    public Roomstatus getRoomstatus() {
		return roomstatus;
	}

	public void setRoomstatus(Roomstatus roomstatus) {
		this.roomstatus = roomstatus;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.roomid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */



	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column room.roomid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer roomid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column room.roomnumber
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private String roomnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column room.roomstatusid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer roomstatusid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column room.buildingid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer buildingid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column room.roomid
	 * @return  the value of room.roomid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getRoomid() {
		return roomid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column room.roomid
	 * @param roomid  the value for room.roomid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setRoomid(Integer roomid) {
		this.roomid = roomid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column room.roomnumber
	 * @return  the value of room.roomnumber
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public String getRoomnumber() {
		return roomnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column room.roomnumber
	 * @param roomnumber  the value for room.roomnumber
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setRoomnumber(String roomnumber) {
		this.roomnumber = roomnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column room.roomstatusid
	 * @return  the value of room.roomstatusid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getRoomstatusid() {
		return roomstatusid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column room.roomstatusid
	 * @param roomstatusid  the value for room.roomstatusid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column room.buildingid
	 * @return  the value of room.buildingid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column room.buildingid
	 * @param buildingid  the value for room.buildingid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.roomstatusid
     *
     * @param roomstatusid the value for room.roomstatusid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setRoomstatusid(Integer roomstatusid) {
        this.roomstatusid = roomstatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.buildingid
     *
     * @return the value of room.buildingid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getBuildingid() {
        return buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.buildingid
     *
     * @param buildingid the value for room.buildingid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setBuildingid(Integer buildingid) {
        this.buildingid = buildingid;
    }

	@Override
	public String toString() {
		return "Room [building=" + building + ", roomstatus=" + roomstatus + ", roomid=" + roomid + ", roomnumber="
				+ roomnumber + ", roomstatusid=" + roomstatusid + ", buildingid=" + buildingid + "]";
	}

}