package com.woniu.entity;

public class Serviceshare extends ServiceshareKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column serviceshare.idnumber
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer idnumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column serviceshare.address
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column serviceshare.share
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer share;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column serviceshare.phone
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column serviceshare.sharetypeid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	private Integer sharetypeid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column serviceshare.idnumber
	 * @return  the value of serviceshare.idnumber
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getIdnumber() {
		return idnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column serviceshare.idnumber
	 * @param idnumber  the value for serviceshare.idnumber
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setIdnumber(Integer idnumber) {
		this.idnumber = idnumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column serviceshare.address
	 * @return  the value of serviceshare.address
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column serviceshare.address
	 * @param address  the value for serviceshare.address
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column serviceshare.share
	 * @return  the value of serviceshare.share
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getShare() {
		return share;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column serviceshare.share
	 * @param share  the value for serviceshare.share
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setShare(Integer share) {
		this.share = share;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column serviceshare.phone
	 * @return  the value of serviceshare.phone
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column serviceshare.phone
	 * @param phone  the value for serviceshare.phone
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column serviceshare.sharetypeid
	 * @return  the value of serviceshare.sharetypeid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Integer getSharetypeid() {
		return sharetypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column serviceshare.sharetypeid
	 * @param sharetypeid  the value for serviceshare.sharetypeid
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setSharetypeid(Integer sharetypeid) {
		this.sharetypeid = sharetypeid;
	}
}