package com.woniu.entity;

public class Service {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.serviceid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer serviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.servicenumber
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private String servicenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.servicetypeid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer servicetypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.servicestatusid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer servicestatusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.proposer
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer proposer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.agent
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer agent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.application
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private String application;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.idcopy
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private String idcopy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.photo
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.purchasecopy
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private String purchasecopy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.contractcopy
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private String contractcopy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.taxcopy
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private String taxcopy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.serviceid
     *
     * @return the value of service.serviceid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getServiceid() {
        return serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.serviceid
     *
     * @param serviceid the value for service.serviceid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setServiceid(Integer serviceid) {
        this.serviceid = serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.servicenumber
     *
     * @return the value of service.servicenumber
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public String getServicenumber() {
        return servicenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.servicenumber
     *
     * @param servicenumber the value for service.servicenumber
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setServicenumber(String servicenumber) {
        this.servicenumber = servicenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.servicetypeid
     *
     * @return the value of service.servicetypeid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getServicetypeid() {
        return servicetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.servicetypeid
     *
     * @param servicetypeid the value for service.servicetypeid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setServicetypeid(Integer servicetypeid) {
        this.servicetypeid = servicetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.servicestatusid
     *
     * @return the value of service.servicestatusid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getServicestatusid() {
        return servicestatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.servicestatusid
     *
     * @param servicestatusid the value for service.servicestatusid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setServicestatusid(Integer servicestatusid) {
        this.servicestatusid = servicestatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.proposer
     *
     * @return the value of service.proposer
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getProposer() {
        return proposer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.proposer
     *
     * @param proposer the value for service.proposer
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setProposer(Integer proposer) {
        this.proposer = proposer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.agent
     *
     * @return the value of service.agent
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getAgent() {
        return agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.agent
     *
     * @param agent the value for service.agent
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setAgent(Integer agent) {
        this.agent = agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.application
     *
     * @return the value of service.application
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public String getApplication() {
        return application;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.application
     *
     * @param application the value for service.application
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setApplication(String application) {
        this.application = application;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.idcopy
     *
     * @return the value of service.idcopy
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public String getIdcopy() {
        return idcopy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.idcopy
     *
     * @param idcopy the value for service.idcopy
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setIdcopy(String idcopy) {
        this.idcopy = idcopy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.photo
     *
     * @return the value of service.photo
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.photo
     *
     * @param photo the value for service.photo
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.purchasecopy
     *
     * @return the value of service.purchasecopy
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public String getPurchasecopy() {
        return purchasecopy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.purchasecopy
     *
     * @param purchasecopy the value for service.purchasecopy
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setPurchasecopy(String purchasecopy) {
        this.purchasecopy = purchasecopy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.contractcopy
     *
     * @return the value of service.contractcopy
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public String getContractcopy() {
        return contractcopy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.contractcopy
     *
     * @param contractcopy the value for service.contractcopy
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setContractcopy(String contractcopy) {
        this.contractcopy = contractcopy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service.taxcopy
     *
     * @return the value of service.taxcopy
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public String getTaxcopy() {
        return taxcopy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service.taxcopy
     *
     * @param taxcopy the value for service.taxcopy
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setTaxcopy(String taxcopy) {
        this.taxcopy = taxcopy;
    }
}