package com.woniu.entity;

import java.util.ArrayList;
import java.util.List;

public class ServiceshareExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table serviceshare
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table serviceshare
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table serviceshare
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table serviceshare
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public ServiceshareExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table serviceshare
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table serviceshare
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table serviceshare
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table serviceshare
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table serviceshare
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table serviceshare
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table serviceshare
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table serviceshare
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table serviceshare
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table serviceshare
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table serviceshare
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andServiceidIsNull() {
			addCriterion("serviceid is null");
			return (Criteria) this;
		}

		public Criteria andServiceidIsNotNull() {
			addCriterion("serviceid is not null");
			return (Criteria) this;
		}

		public Criteria andServiceidEqualTo(Integer value) {
			addCriterion("serviceid =", value, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidNotEqualTo(Integer value) {
			addCriterion("serviceid <>", value, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidGreaterThan(Integer value) {
			addCriterion("serviceid >", value, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidGreaterThanOrEqualTo(Integer value) {
			addCriterion("serviceid >=", value, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidLessThan(Integer value) {
			addCriterion("serviceid <", value, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidLessThanOrEqualTo(Integer value) {
			addCriterion("serviceid <=", value, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidIn(List<Integer> values) {
			addCriterion("serviceid in", values, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidNotIn(List<Integer> values) {
			addCriterion("serviceid not in", values, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidBetween(Integer value1, Integer value2) {
			addCriterion("serviceid between", value1, value2, "serviceid");
			return (Criteria) this;
		}

		public Criteria andServiceidNotBetween(Integer value1, Integer value2) {
			addCriterion("serviceid not between", value1, value2, "serviceid");
			return (Criteria) this;
		}

		public Criteria andClientidIsNull() {
			addCriterion("clientid is null");
			return (Criteria) this;
		}

		public Criteria andClientidIsNotNull() {
			addCriterion("clientid is not null");
			return (Criteria) this;
		}

		public Criteria andClientidEqualTo(Integer value) {
			addCriterion("clientid =", value, "clientid");
			return (Criteria) this;
		}

		public Criteria andClientidNotEqualTo(Integer value) {
			addCriterion("clientid <>", value, "clientid");
			return (Criteria) this;
		}

		public Criteria andClientidGreaterThan(Integer value) {
			addCriterion("clientid >", value, "clientid");
			return (Criteria) this;
		}

		public Criteria andClientidGreaterThanOrEqualTo(Integer value) {
			addCriterion("clientid >=", value, "clientid");
			return (Criteria) this;
		}

		public Criteria andClientidLessThan(Integer value) {
			addCriterion("clientid <", value, "clientid");
			return (Criteria) this;
		}

		public Criteria andClientidLessThanOrEqualTo(Integer value) {
			addCriterion("clientid <=", value, "clientid");
			return (Criteria) this;
		}

		public Criteria andClientidIn(List<Integer> values) {
			addCriterion("clientid in", values, "clientid");
			return (Criteria) this;
		}

		public Criteria andClientidNotIn(List<Integer> values) {
			addCriterion("clientid not in", values, "clientid");
			return (Criteria) this;
		}

		public Criteria andClientidBetween(Integer value1, Integer value2) {
			addCriterion("clientid between", value1, value2, "clientid");
			return (Criteria) this;
		}

		public Criteria andClientidNotBetween(Integer value1, Integer value2) {
			addCriterion("clientid not between", value1, value2, "clientid");
			return (Criteria) this;
		}

		public Criteria andIdnumberIsNull() {
			addCriterion("idnumber is null");
			return (Criteria) this;
		}

		public Criteria andIdnumberIsNotNull() {
			addCriterion("idnumber is not null");
			return (Criteria) this;
		}

		public Criteria andIdnumberEqualTo(Integer value) {
			addCriterion("idnumber =", value, "idnumber");
			return (Criteria) this;
		}

		public Criteria andIdnumberNotEqualTo(Integer value) {
			addCriterion("idnumber <>", value, "idnumber");
			return (Criteria) this;
		}

		public Criteria andIdnumberGreaterThan(Integer value) {
			addCriterion("idnumber >", value, "idnumber");
			return (Criteria) this;
		}

		public Criteria andIdnumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("idnumber >=", value, "idnumber");
			return (Criteria) this;
		}

		public Criteria andIdnumberLessThan(Integer value) {
			addCriterion("idnumber <", value, "idnumber");
			return (Criteria) this;
		}

		public Criteria andIdnumberLessThanOrEqualTo(Integer value) {
			addCriterion("idnumber <=", value, "idnumber");
			return (Criteria) this;
		}

		public Criteria andIdnumberIn(List<Integer> values) {
			addCriterion("idnumber in", values, "idnumber");
			return (Criteria) this;
		}

		public Criteria andIdnumberNotIn(List<Integer> values) {
			addCriterion("idnumber not in", values, "idnumber");
			return (Criteria) this;
		}

		public Criteria andIdnumberBetween(Integer value1, Integer value2) {
			addCriterion("idnumber between", value1, value2, "idnumber");
			return (Criteria) this;
		}

		public Criteria andIdnumberNotBetween(Integer value1, Integer value2) {
			addCriterion("idnumber not between", value1, value2, "idnumber");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andShareIsNull() {
			addCriterion("share is null");
			return (Criteria) this;
		}

		public Criteria andShareIsNotNull() {
			addCriterion("share is not null");
			return (Criteria) this;
		}

		public Criteria andShareEqualTo(Integer value) {
			addCriterion("share =", value, "share");
			return (Criteria) this;
		}

		public Criteria andShareNotEqualTo(Integer value) {
			addCriterion("share <>", value, "share");
			return (Criteria) this;
		}

		public Criteria andShareGreaterThan(Integer value) {
			addCriterion("share >", value, "share");
			return (Criteria) this;
		}

		public Criteria andShareGreaterThanOrEqualTo(Integer value) {
			addCriterion("share >=", value, "share");
			return (Criteria) this;
		}

		public Criteria andShareLessThan(Integer value) {
			addCriterion("share <", value, "share");
			return (Criteria) this;
		}

		public Criteria andShareLessThanOrEqualTo(Integer value) {
			addCriterion("share <=", value, "share");
			return (Criteria) this;
		}

		public Criteria andShareIn(List<Integer> values) {
			addCriterion("share in", values, "share");
			return (Criteria) this;
		}

		public Criteria andShareNotIn(List<Integer> values) {
			addCriterion("share not in", values, "share");
			return (Criteria) this;
		}

		public Criteria andShareBetween(Integer value1, Integer value2) {
			addCriterion("share between", value1, value2, "share");
			return (Criteria) this;
		}

		public Criteria andShareNotBetween(Integer value1, Integer value2) {
			addCriterion("share not between", value1, value2, "share");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("phone is null");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("phone is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("phone =", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("phone <>", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("phone >", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("phone >=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("phone <", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("phone <=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("phone like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("phone not like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneIn(List<String> values) {
			addCriterion("phone in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotIn(List<String> values) {
			addCriterion("phone not in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("phone between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("phone not between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andSharetypeidIsNull() {
			addCriterion("sharetypeid is null");
			return (Criteria) this;
		}

		public Criteria andSharetypeidIsNotNull() {
			addCriterion("sharetypeid is not null");
			return (Criteria) this;
		}

		public Criteria andSharetypeidEqualTo(Integer value) {
			addCriterion("sharetypeid =", value, "sharetypeid");
			return (Criteria) this;
		}

		public Criteria andSharetypeidNotEqualTo(Integer value) {
			addCriterion("sharetypeid <>", value, "sharetypeid");
			return (Criteria) this;
		}

		public Criteria andSharetypeidGreaterThan(Integer value) {
			addCriterion("sharetypeid >", value, "sharetypeid");
			return (Criteria) this;
		}

		public Criteria andSharetypeidGreaterThanOrEqualTo(Integer value) {
			addCriterion("sharetypeid >=", value, "sharetypeid");
			return (Criteria) this;
		}

		public Criteria andSharetypeidLessThan(Integer value) {
			addCriterion("sharetypeid <", value, "sharetypeid");
			return (Criteria) this;
		}

		public Criteria andSharetypeidLessThanOrEqualTo(Integer value) {
			addCriterion("sharetypeid <=", value, "sharetypeid");
			return (Criteria) this;
		}

		public Criteria andSharetypeidIn(List<Integer> values) {
			addCriterion("sharetypeid in", values, "sharetypeid");
			return (Criteria) this;
		}

		public Criteria andSharetypeidNotIn(List<Integer> values) {
			addCriterion("sharetypeid not in", values, "sharetypeid");
			return (Criteria) this;
		}

		public Criteria andSharetypeidBetween(Integer value1, Integer value2) {
			addCriterion("sharetypeid between", value1, value2, "sharetypeid");
			return (Criteria) this;
		}

		public Criteria andSharetypeidNotBetween(Integer value1, Integer value2) {
			addCriterion("sharetypeid not between", value1, value2, "sharetypeid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table serviceshare
	 * @mbg.generated  Mon Aug 19 16:10:36 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table serviceshare
     *
     * @mbg.generated do_not_delete_during_merge Mon Aug 19 15:45:31 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}