package com.woniu.entity;

public class Servicesharetemporary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicesharetemporary.shareid
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private Integer shareid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicesharetemporary.rtid
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private Integer rtid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicesharetemporary.sharename
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String sharename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicesharetemporary.shareidcard
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String shareidcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicesharetemporary.shareaddresss
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String shareaddresss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicesharetemporary.sharetype
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String sharetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicesharetemporary.share
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private Double share;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicesharetemporary.sharetel
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    private String sharetel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicesharetemporary.shareid
     *
     * @return the value of servicesharetemporary.shareid
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public Integer getShareid() {
        return shareid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicesharetemporary.shareid
     *
     * @param shareid the value for servicesharetemporary.shareid
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setShareid(Integer shareid) {
        this.shareid = shareid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicesharetemporary.rtid
     *
     * @return the value of servicesharetemporary.rtid
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public Integer getRtid() {
        return rtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicesharetemporary.rtid
     *
     * @param rtid the value for servicesharetemporary.rtid
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setRtid(Integer rtid) {
        this.rtid = rtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicesharetemporary.sharename
     *
     * @return the value of servicesharetemporary.sharename
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getSharename() {
        return sharename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicesharetemporary.sharename
     *
     * @param sharename the value for servicesharetemporary.sharename
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setSharename(String sharename) {
        this.sharename = sharename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicesharetemporary.shareidcard
     *
     * @return the value of servicesharetemporary.shareidcard
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getShareidcard() {
        return shareidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicesharetemporary.shareidcard
     *
     * @param shareidcard the value for servicesharetemporary.shareidcard
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setShareidcard(String shareidcard) {
        this.shareidcard = shareidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicesharetemporary.shareaddresss
     *
     * @return the value of servicesharetemporary.shareaddresss
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getShareaddresss() {
        return shareaddresss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicesharetemporary.shareaddresss
     *
     * @param shareaddresss the value for servicesharetemporary.shareaddresss
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setShareaddresss(String shareaddresss) {
        this.shareaddresss = shareaddresss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicesharetemporary.sharetype
     *
     * @return the value of servicesharetemporary.sharetype
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getSharetype() {
        return sharetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicesharetemporary.sharetype
     *
     * @param sharetype the value for servicesharetemporary.sharetype
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setSharetype(String sharetype) {
        this.sharetype = sharetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicesharetemporary.share
     *
     * @return the value of servicesharetemporary.share
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public Double getShare() {
        return share;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicesharetemporary.share
     *
     * @param share the value for servicesharetemporary.share
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setShare(Double share) {
        this.share = share;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicesharetemporary.sharetel
     *
     * @return the value of servicesharetemporary.sharetel
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public String getSharetel() {
        return sharetel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicesharetemporary.sharetel
     *
     * @param sharetel the value for servicesharetemporary.sharetel
     *
     * @mbg.generated Wed Aug 21 14:57:48 CST 2019
     */
    public void setSharetel(String sharetel) {
        this.sharetel = sharetel;
    }
}