package com.woniu.entity;

public class Servicetype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicetype.servicetypeid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer servicetypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servicetype.servicetype
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private String servicetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicetype.servicetypeid
     *
     * @return the value of servicetype.servicetypeid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getServicetypeid() {
        return servicetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicetype.servicetypeid
     *
     * @param servicetypeid the value for servicetype.servicetypeid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setServicetypeid(Integer servicetypeid) {
        this.servicetypeid = servicetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servicetype.servicetype
     *
     * @return the value of servicetype.servicetype
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public String getServicetype() {
        return servicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servicetype.servicetype
     *
     * @param servicetype the value for servicetype.servicetype
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setServicetype(String servicetype) {
        this.servicetype = servicetype;
    }
}