package com.woniu.entity;

public class Sharetype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharetype.sharetypeid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private Integer sharetypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharetype.sharetype
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    private String sharetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharetype.sharetypeid
     *
     * @return the value of sharetype.sharetypeid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public Integer getSharetypeid() {
        return sharetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharetype.sharetypeid
     *
     * @param sharetypeid the value for sharetype.sharetypeid
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setSharetypeid(Integer sharetypeid) {
        this.sharetypeid = sharetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharetype.sharetype
     *
     * @return the value of sharetype.sharetype
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public String getSharetype() {
        return sharetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharetype.sharetype
     *
     * @param sharetype the value for sharetype.sharetype
     *
     * @mbg.generated Mon Aug 19 15:45:31 CST 2019
     */
    public void setSharetype(String sharetype) {
        this.sharetype = sharetype;
    }
}